version: "3"
services:
  i2kit:
    image: pchico83/i2kit
    build: .
    environment:
      - AWS_SHARED_CREDENTIALS_FILE=/run/secrets/aws-credentials
      - AWS_REGION=us-west-2
    volumes:
      - $PWD/aws-credentials:/run/secrets/aws-credentials
      - ~/.docker/config.json:/root/.docker/config.json
      - ~/.ssh/id_rsa.pub:/root/.ssh/id_rsa.pub
      - /var/run/docker.sock:/var/run/docker.sock
