version: "3.4"
services:
  nginx:
    image: nginx:alpine
    command: start.sh
    ports:
    - 80:80
    environment:
    - NAME=VALUE
    logging:
      driver: awslogs
      options:
        awslogs-group: i2kit-test-staging
        awslogs-region: us-west-2
        tag: nginx-${INSTANCE_ID}
    restart: on-failure
    dns_search:
    - staging.i2kit.com
