type: "//rec"
required:
  name: "//str"
  containers:
    type: "//map"
    values:
      type: "//rec"
      required:
        image: "//str"
      optional:
        command: "//str"
        envvars:
          type: "//arr"
          contents: "//str"
        ports:
          type: "//arr"
          contents: "//str"
optional:
  public: "//bool"
  stateful: "//bool"
  replicas: "//int"
  size: "//str"
