name: test
provider:
  instance_type: t2.small
  certificate: arn:aws:acm:us-west-2:062762192540:certificate/12de3ac5-abcd-461a-1234-9e81250b33d8
  access_key: accesskey
  secret_key: secretkey
  region: us-west-2
  subnets:
  - subnet-7c75725
  - subnet-7c75726
  security_group: sg-dffe41a3
  keypair: development
  hosted_zone: example.com.
docker:
  username: test
  password: password
