type: "//rec"
required:
  name: "//str"
optional:
  provider:
    type: "//rec"
    required:
      name: "//str"
      access_key: "//str"
      secret_key: "//str"
      region: "//str"
      subnets:
        type: "//arr"
        contents: "//str"
      security_group: "//str"
      keypair: "//str"
      hosted_zone: "//str"
    optional:
      certificate: "//str"
      instance_type: "//str"
  docker:
    type: "//rec"
    required:
      username: "//str"
      password: "//str"
