version: "3"
services:
  agent:
    image: riberaproject/agent
    build: .
    environment:
      - CONFIG
      - COMPOSE
      - STACK
      - REGION
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
